### ISSUE TITLE
大佬救命啊，我用vercel部署了，但是发出信息后发送按钮一直转圈圈

### ISSUE THREAD

**Issue by getofferhelp** [circle-hotaru/talk-boost#43]
是哪个没设置对吗

<img width="377" alt="0009" src="https://github.com/circle-hotaru/talk-boost-ai/assets/13744916/24787037-d563-4165-ac32-ef1727927edc">

**Comment by getofferhelp** [comment]
database url 和direct url 后面分别是6543、5432，我也设置了啊，就一只不能正常运行，log里面也没有发出信息的记录，懵逼了，大佬救命啊

**Comment by circle-hotaru** [comment]
你是本地能允许，但是部署到 vercel 上就不行？
转圈圈的大概率是 openAI 没拿到响应，能否控制台网络那里检查下响应？

**Comment by getofferhelp** [comment]
> 你是本地能允许，但是部署到 vercel 上就不行？ 转圈圈的大概率是 openAI 没拿到响应，能否控制台网络那里检查下响应？

后来解决了，以我一种不能理解的方式- -！

我先把proxy删除了然后魔法可用，关闭魔法不可用；关闭魔法，然后把proxy加上去，又可用了。。。

而原本是关闭魔法+proxy，不可用。百思不得其解

**Comment by getofferhelp** [comment]
感谢大佬回复

**Comment by circle-hotaru** [comment]
不客气，确实是不可思议的解决方法🤣
