### ISSUE TITLE
大佬， 关于语音发送信息时多语言识别

### ISSUE THREAD

**Issue by tiwentichat** [circle-hotaru/talk-boost#44]
我想改成其他小语种也能用，但是实际情况是只能识别为英文。

代码我看了，好像没有指定只识别英文啊

我还怀疑过是不是因为azure region我选的eastus，不过重新创建资源时选了优先中文、eastasia后也还是不生肖
大佬知道是因为什么原因吗？

求回复，感谢！

**Comment by tiwentichat** [comment]
补充：做过几个测试，gpt的回复可以多语种，但是我发信息只能英语

**Comment by tiwentichat** [comment]
二次补充：刚才在另一个Repo上(speechgpt)试了一下，发现让azure默认识别中文的话，是可以多语言识别的；但是这儿我找了好久没发现为啥会默认只识别英文   T T

**Comment by circle-hotaru** [comment]
可以试试配置
```
speechConfig.speechRecognitionLanguage = language;
```

https://github.com/circle-hotaru/talk-boost-ai/blob/20d1dca67394a34c3ee54ad0a3a0c5f6ece1df50/src/apis/azureTTS.ts#L23-L26

**Comment by tiwentichat** [comment]
> 可以试试配置
> 
> ```
> speechConfig.speechRecognitionLanguage = language;
> ```
> 
> https://github.com/circle-hotaru/talk-boost-ai/blob/20d1dca67394a34c3ee54ad0a3a0c5f6ece1df50/src/apis/azureTTS.ts#L23-L26

啊，搞定！
感谢大佬指导！

以及一个感慨：AI最开始告诉我了这样设置，而且直接给的是language 设置为zh-CN, 但是我觉得那样就把被识别语言限定为单一语言了。 就没尝试

结果兜兜转转还是用了这个方案，感慨....

**Comment by circle-hotaru** [comment]
或许还有其他更智能的语音识别服务。不过你要支持小语种的话，可以让在界面中提供语言选项让用户选择，然后动态配置 speechConfig 也行
